name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main docs repo
        uses: actions/checkout@v2
      - run: wget https://github.com/kubewarden/mdBook/releases/download/anonymize-ip/mdbook-anonymize-ip-x86_64-unknown-linux-gnu.tar.gz
      - run: tar xf mdbook-anonymize-ip-x86_64-unknown-linux-gnu.tar.gz
      - run: ./mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
